### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by a449139686** [saiwu-bigkoo/Android-ConvenientBanner#140]
Process: com.uksurprise.android.uksurprice, PID: 7470
                                                                                 java.lang.StackOverflowError: stack size 8MB
                                                                                     at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:632)
                                                                                     at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:628)
                                                                                     at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:620)
                                                                                     at com.bigkoo.convenientbanner.adapter.CBPageAdapter.finishUpdate(CBPageAdapter.java:67)
                                                                                     at android.support.v4.view.ViewPager.populate(ViewPager.java:1235)
                                                                                     at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:666)
                                                                                     at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:628)
                                                                                     at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:620)
                                                                                     at com.bigkoo.convenientbanner.adapter.CBPageAdapter.finishUpdate(CBPageAdapter.java:67)
                                                                                     at android.support.v4.view.ViewPager.populate(ViewPager.java:1235)
                                                                                     at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:666)
                                                                                     at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:628)
                                                                                     at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:620)
                                                                                     at com.bigkoo.convenientbanner.adapter.CBPageAdapter.finishUpdate(CBPageAdapter.java:67)
                                                                                     at android.support.v4.view.ViewPager.populate(ViewPager.java:1235)
                                                                                     at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:666)
                                                                                     at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:628)
                                                                                     at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:620)
                                                                                     at com.bigkoo.convenientbanner.adapter.CBPageAdapter.finishUpdate(CBPageAdapter.java:67)
                                                                                     at android.support.v4.view.ViewPager.populate(ViewPager.java:1235)
                                                                                     at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:666)
                                                                                     at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:628)
                                                                                     at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:620)
                                                                                     at com.bigkoo.convenientbanner.adapter.CBPageAdapter.finishUpdate(CBPageAdapter.java:67)
                                                                                     at android.support.v4.view.ViewPager.populate(ViewPager.java:1235)
                                                                                     at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:666)
                                                                                     at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:628)
                                                                                     at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:620)
                                                                                     at com.bigkoo.convenientbanner.adapter.CBPageAdapter.finishUpdate(CBPageAdapter.java:67)
                                                                                     at android.support.v4.view.ViewPager.populate(ViewPager.java:1235)
                                                                                     at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:666)
                                                                                     at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:628)
                                                                                     at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:620)
                                                                                     at com.bigkoo.convenientbanner.adapter.CBPageAdapter.finishUpdate(CBPageAdapter.java:67)
                                                                                     at android.support.v4.view.ViewPager.populate(ViewPager.java:1235)
                                                                                     at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:666)
                                                                                     at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:628)
                                                                                     at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:620)
                                                                                     at com.bigkoo.convenientbanner.adapter.CBPageAdapter.finishUpdate(CBPageAdapter.java:67)
                                                                                     at android.support.v4.view.ViewPager.populate(ViewPager.java:1235)
                                                                                     at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:666)
                                                                                     at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:628)
                                                                                     at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:620)
                                                                                     at com.bigkoo.convenientbanner.adapter.CBPageAdapter.finishUpdate(CBPageAdapter.java:67)
                                                                                     at android.support.v4.view.ViewPager.populate(ViewPager.java:1235)
                                                                                     at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:666)
                                                                                     at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:628)
                                                                                     at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:620)
                                                                                     at com.bigkoo.convenientbanner.adapter.CBPageAdapter.finishUpdate(CBPageAdapter.java:67)
                                                                                     at android.support.v4.view.ViewPager.populate(ViewPager.java:1235)
                                                                                 	at andr

**Comment by a449139686** [comment]
Error reporting crash
                                                                                 android.os.TransactionTooLargeException: data parcel size 17864532 bytes
                                                                                     at android.os.BinderProxy.transactNative(Native Method)
                                                                                     at android.os.BinderProxy.transact(Binder.java:503)
                                                                                     at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4425)
                                                                                     at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:90)
                                                                                     at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                                                     at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)

**Comment by saiwu-bigkoo** [comment]
是不是图片超大

**Comment by applePuff** [comment]
那么建议用多大的图片比较好呢？

**Comment by SmallPeas** [comment]
http://www.cnblogs.com/Soprano/articles/2577152.html  最好使用压缩的图片




------------------ 原始邮件 ------------------
发件人: "applePuff";<notifications@github.com>;
发送时间: 2016年8月16日(星期二) 上午10:18
收件人: "saiwu-bigkoo/Android-ConvenientBanner"<Android-ConvenientBanner@noreply.github.com>; 

主题: Re: [saiwu-bigkoo/Android-ConvenientBanner] StackOverflowError (#140)




那么建议用多大的图片比较好呢？
