### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by applePuff** [saiwu-bigkoo/Android-ConvenientBanner#145]
java.lang.OutOfMemoryError
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:694)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:519)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:889)
	at android.content.res.Resources.loadDrawable(Resources.java:3428)
	at android.content.res.Resources.getDrawable(Resources.java:1901)
	at android.widget.ImageView.resolveUri(ImageView.java:648)
	at android.widget.ImageView.setImageResource(ImageView.java:377)
	at com.xxjsskfk.demo.base.LocalImageHolderView.UpdateUI(LocalImageHolderView.java:24)
	at com.xxjsskfk.demo.base.LocalImageHolderView.UpdateUI(LocalImageHolderView.java:13)
	at com.bigkoo.convenientbanner.adapter.CBPageAdapter.getView(CBPageAdapter.java:99)
	at com.bigkoo.convenientbanner.adapter.CBPageAdapter.instantiateItem(CBPageAdapter.java:46)
	at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:943)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1157)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:608)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:570)
	at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:551)
	at com.bigkoo.convenientbanner.ConvenientBanner$AdSwitchTask.run(ConvenientBanner.java:110)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5653)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
	at dalvik.system.NativeStart.main(Native Method)

直接把demo里的LocalImageHolderView拷过去的啊，把banner放在了一个fragment里面。
为什么会报内存溢出呢？

**Comment by saiwu-bigkoo** [comment]
是你的Image超大，Bitmap都爆了
