### ISSUE TITLE
The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 1800, found: 0 Pager id: cn.missevan:id/cbLoopViewPager Pager class: class com.bigkoo.convenientbanner.view.CBLoopViewPager Problematic adapter: class com.bigkoo.convenientbanner.adapter.CBPageAdapter

### ISSUE THREAD

**Issue by 15806905685** [saiwu-bigkoo/Android-ConvenientBanner#177]
下面是错误log，出现的情况是我在fragment加了banner，然后刷新的时候，调用notifyDataSetChanged()，并不是每次都会出现，但是很容易出现。
java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 1800, found: 0 Pager id: cn.missevan:id/cbLoopViewPager Pager class: class com.bigkoo.convenientbanner.view.CBLoopViewPager Problematic adapter: class com.bigkoo.convenientbanner.adapter.CBPageAdapter
                                                                 at android.support.v4.view.ViewPager.populate(ViewPager.java:1000)
                                                                 at android.support.v4.view.ViewPager.populate(ViewPager.java:952)
                                                                 at android.support.v4.view.ViewPager$3.run(ViewPager.java:251)
                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:818)
                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:621)
                                                                 at android.view.Choreographer.doFrame(Choreographer.java:583)
                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:804)
                                                                 at android.os.Handler.handleCallback(Handler.java:815)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                 at android.os.Looper.loop(Looper.java:194)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:5691)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

**Comment by 15806905685** [comment]
问题找到了，因为刷新的时候要重新获取数据，这个时候原本传给banner的list需要clear一下，然后add进新的数据。当在轮播的一瞬间的时候（也就是切换到一半的时候）触发刷新的方法，此时list执行了clear之后变成空的，于是出现了这个错误。再往下的话应该就是populate()方法在调用的时候，list为空导致的。因为在切换的过程中会调用notifyDataSetChanged()。
