### ISSUE TITLE
2.0.5 刷新奇葩崩溃BUG

### ISSUE THREAD

**Issue by YougaKing** [saiwu-bigkoo/Android-ConvenientBanner#179]
![image](https://cloud.githubusercontent.com/assets/16010591/19801169/aad85fe4-9d30-11e6-8253-f8f1fbee7c2a.png)
                                                                                 Process: com.liyuan.youga.marrysecretary, PID: 17272
                                                                                 java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 1500, found: 0 Pager id: com.liyuan.youga.marrysecretary:id/cbLoopViewPager Pager class: class com.bigkoo.convenientbanner.view.CBLoopViewPager Problematic adapter: class com.bigkoo.convenientbanner.adapter.CBPageAdapter
                                                                                     at android.support.v4.view.ViewPager.populate(ViewPager.java:1071)
                                                                                     at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
                                                                                     at android.support.v4.view.ViewPager$3.run(ViewPager.java:254)
                                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                                     at android.view.Choreographer.doFrame(Choreographer.java:618)
                                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                                     at android.os.Handler.handleCallback(Handler.java:751)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by YougaKing** [comment]
主要是这句，没详细看过你的代码，请速速修复。
java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 1500, found: 0 Pager id: com.liyuan.youga.marrysecretary:id/cbLoopViewPager Pager class: class com.bigkoo.convenientbanner.view.CBLoopViewPager Problematic adapter: class com.bigkoo.convenientbanner.adapter.CBPageAdapter

**Comment by yangxiaoge** [comment]
我也碰到跟你一样的问题, 偶尔会复现. 一直没有解决的办法, 囧~~~
