### ISSUE TITLE
在xml里面设置 app:canLoop="false" 后   切换fragment出现这个错误    在fragment里面设置没问题

### ISSUE THREAD

**Issue by twlk-jzy** [saiwu-bigkoo/Android-ConvenientBanner#186]
ERR: stack=java.lang.StackOverflowError: stack size 8MB
                                                             at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:574)
                                                             at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:570)
                                                             at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:562)
                                                             at com.bigkoo.convenientbanner.adapter.CBPageAdapter.finishUpdate(CBPageAdapter.java:67)
                                                             at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
                                                             at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:608)
                                                             at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:570)
                                                             at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:562)
                                                             at com.bigkoo.convenientbanner.adapter.CBPageAdapter.finishUpdate(CBPageAdapter.java:67)
                                                             at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
                                                             at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:608)
                                                             at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:570)
                                                             at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:562)
                                                             at com.bigkoo.convenientbanner.adapter.CBPageAdapter.finishUpdate(CBPageAdapter.java:67)
                                                             at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
                                                             at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:608)
                                                             at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:570)
                                                             at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:562)
                                                             at com.bigkoo.convenientbanner.adapter.CBPageAdapter.finishUpdate(CBPageAdapter.java:67)
                                                             at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
                                                             at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:608)
                                                             at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:570)
                                                             at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:562)
                                                             at com.bigkoo.convenientbanner.adapter.CBPageAdapter.finishUpdate(CBPageAdapter.java:67)
                                                             at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
                                                             at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:608)
                                                             at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:570)
                                                             at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:562)
                                                             at com.bigkoo.convenientbanner.adapter.CBPageAdapter.finishUpdate(CBPageAdapter.java:67)
                                                             at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
                                                             at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:608)
                                                             at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:570)
                                                             at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:562)
                                                             at com.bigkoo.convenientbanner.adapter.CBPageAdapter.finishUpdate(CBPageAdapter.java:67)
                                                             at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
                                                             at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:608)
                                                             at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:570)
                                                             at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:562)
                                                             at com.bigkoo.convenientbanner.adapter.CBPageAdapter.finishUpdate(CBPageAdapter.java:67)
                                                             at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
                                                             at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:608)
                                                             at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:570)
                                                             at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:562)
                                                             at com.bigkoo.convenientbanner.adapter.CBPageAdapter.finishUpdate(CBPageAdapter.java:67)
                                                             at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
                                                             at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:608)
                                                             at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:570)
                                                             at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:562)
                                                             at com.bigkoo.convenientbanner.adapter.CBPageAdapter.finishUpdate(CBPageAdapter.java:67)
                                                             at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
                                                             at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:608)

**Comment by caofei0** [comment]
这不是我的项目，你找错人了，你去问原来写项目的吧

At 2016-11-17 11:25:55, "twlk-jzy" <notifications@github.com> wrote:


ERR: stack=java.lang.StackOverflowError: stack size 8MB
at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:574)
at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:570)
at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:562)
at com.bigkoo.convenientbanner.adapter.CBPageAdapter.finishUpdate(CBPageAdapter.java:67)
at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:608)
at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:570)
at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:562)
at com.bigkoo.convenientbanner.adapter.CBPageAdapter.finishUpdate(CBPageAdapter.java:67)
at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:608)
at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:570)
at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:562)
at com.bigkoo.convenientbanner.adapter.CBPageAdapter.finishUpdate(CBPageAdapter.java:67)
at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:608)
at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:570)
at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:562)
at com.bigkoo.convenientbanner.adapter.CBPageAdapter.finishUpdate(CBPageAdapter.java:67)
at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:608)
at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:570)
at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:562)
at com.bigkoo.convenientbanner.adapter.CBPageAdapter.finishUpdate(CBPageAdapter.java:67)
at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:608)
at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:570)
at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:562)
at com.bigkoo.convenientbanner.adapter.CBPageAdapter.finishUpdate(CBPageAdapter.java:67)
at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:608)
at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:570)
at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:562)
at com.bigkoo.convenientbanner.adapter.CBPageAdapter.finishUpdate(CBPageAdapter.java:67)
at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:608)
at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:570)
at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:562)
at com.bigkoo.convenientbanner.adapter.CBPageAdapter.finishUpdate(CBPageAdapter.java:67)
at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:608)
at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:570)
at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:562)
at com.bigkoo.convenientbanner.adapter.CBPageAdapter.finishUpdate(CBPageAdapter.java:67)
at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:608)
at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:570)
at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:562)
at com.bigkoo.convenientbanner.adapter.CBPageAdapter.finishUpdate(CBPageAdapter.java:67)
at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:608)

**Comment by twlk-jzy** [comment]
Well, I'm sorry.

**Comment by xueyaolive** [comment]
你的list大小不能等于0或者1，这是一个bug，只有设置app:canLoop="true"
