### ISSUE TITLE
通过logcat发现bug。

### ISSUE THREAD

**Issue by wusir-china** [saiwu-bigkoo/Android-ConvenientBanner#347]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v7.widget.RecyclerView$LayoutManager com.bigkoo.convenientbanner.view.CBLoopViewPager.getLayoutManager()' on a null object reference

**Comment by wusir-china** [comment]
我的不是图片翻页，我这是在ConvenientBanner的子布局中加了recyclerview翻页的，结果报了以上错误。但我不确定是不是因为用了recyclerview才导致的。
java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v7.widget.RecyclerView$LayoutManager com.bigkoo.convenientbanner.view.CBLoopViewPager.getLayoutManager()' on a null object reference
2019-08-02 09:57:23.569 27660-27660/com.xxx.xx W/System.err:     at com.bigkoo.convenientbanner.helper.CBLoopScaleHelper.getCurrentItem(CBLoopScaleHelper.java:129)
2019-08-02 09:57:23.569 27660-27660/com.xxx.xx W/System.err:     at com.bigkoo.convenientbanner.ConvenientBanner$AdSwitchTask.run(ConvenientBanner.java:304)

**Comment by wusir-china** [comment]
我找到解决办法了，原来是我在onresume中调用了convenientBanner.startTurning(3000);方法，而此时数据还未成功获得。就会报上述错误，只需要把这个方法在成功获取数据后在convenientBanner.setPages()后调用，但是如果不在onresume中设置的话，离开后我在onpause中调用的convenientBanner.stopTurning()会导致停止轮播，在返回时就不轮播了。

**Comment by wusir-china** [comment]
只能在onresume中进行数据获取和播放了
