### ISSUE TITLE
建议在CBLoopViewPager的super.setCurrentItem(realItem, smoothScroll);用try－catch一下

### ISSUE THREAD

**Issue by caixuejian** [saiwu-bigkoo/Android-ConvenientBanner#40]
java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 2, found: 4 Pager id: com.rjfittime.app:id/cbLoopViewPager Pager class: class com.bigkoo.convenientbanner.CBLoopViewPager Problematic adapter: class com.bigkoo.convenientbanner.CBLoopPagerAdapterWrapper
            at android.support.v4.view.ViewPager.populate(ViewPager.java:1000)
            at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:552)
            at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:514)
            at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:506)
            at com.bigkoo.convenientbanner.CBLoopViewPager.setCurrentItem(CBLoopViewPager.java:132)
            at com.bigkoo.convenientbanner.CBLoopViewPager.setCurrentItem(CBLoopViewPager.java:138)
            at com.bigkoo.convenientbanner.ConvenientBanner$1.run(ConvenientBanner.java:75)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5942)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)

**Comment by saiwu-bigkoo** [comment]
请问你当前使用的版本是？

**Comment by caixuejian** [comment]
最新版本 刚才的问题已经解决！现在主要问题是 把他放在listview作为header时 从下面往上滚出来的时候总是会先白一下 才能加载出来图片

**Comment by saiwu-bigkoo** [comment]
我测试了下没有先白一下再出图，你能否提供一个有这个问题demo给我看看呢？
