### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by nukc** [saiwu-bigkoo/Android-ConvenientBanner#51]
网络请求超时后报错

```java
com.android.volley.TimeoutError


E/AndroidRuntime: FATAL EXCEPTION: main    Process: com.fangbei.market, PID: 28280
java.lang.NullPointerException , 
  at com.bigkoo.convenientbanner.ConvenientBanner$1.run(ConvenientBanner.java:88)
  at android.os.Handler.handleCallback(Handler.java:733)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:136)
  at android.app.ActivityThread.main(ActivityThread.java:5001)
  at java.lang.reflect.Method.invokeNative(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
  at dalvik.system.NativeStart.main(Native Method)
```

**Comment by nukc** [comment]
版本是2.0.0

**Comment by saiwu-bigkoo** [comment]
你是不是还没设置 adapter就开始 start翻页动画了？

**Comment by nukc** [comment]
是在onResume()里startTurning的，那明白了，setPages是在网络请求成功后设置的。
我现在已经加了变量控制。

```java
private boolean isBannerSetted = false; 
在setPages后 isBannerSetted = true;

@Override
    public void onResume() {
        super.onResume();
        //开始自动翻页
        if (isBannerSetted) {
            convenientBanner.startTurning(5000);
        }
    }

@Override
    public void onPause() {
        super.onPause();
        //停止翻页
        if (isBannerSetted) {
            convenientBanner.stopTurning();
        }
    }
```

**Comment by saiwu-bigkoo** [comment]
OK，我也会在下版本中添加下判断如果adapter没设置就不让翻。
