### ISSUE TITLE
NullPointerException异常 ？请问是为什么呢？

### ISSUE THREAD

**Issue by pickyourself** [saiwu-bigkoo/Android-ConvenientBanner#65]
我的代码：
 convenientBanner.setOnItemClickListener(new OnItemClickListener() {
            @Override
            public void onItemClick(int position) {
                Log.d("123","wwww");
            }
        });

异常信息：  Process: com.yajiangwangluo.kameilian, PID: 23222
                                                   java.lang.NullPointerException
                                                       at com.bigkoo.convenientbanner.ConvenientBanner.setOnItemClickListener(ConvenientBanner.java:294)
                                                       at com.yajiangwangluo.fragment.ActivitiesFragment.onViewCreated(ActivitiesFragment.java:112)
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1086)
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
                                                       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
                                                       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
                                                       at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
                                                       at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
                                                       at android.support.v4.view.ViewPager.populate(ViewPager.java:1106)
                                                       at android.support.v4.view.ViewPager.populate(ViewPager.java:952)
                                                       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1474)
                                                       at android.view.View.measure(View.java:16892)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5394)
                                                       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1647)
                                                       at android.widget.LinearLayout.measureVertical(LinearLayout.java:763)
                                                       at android.widget.LinearLayout.onMeasure(LinearLayout.java:628)
                                                       at android.view.View.measure(View.java:16892)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5394)
                                                       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1647)
                                                       at android.widget.LinearLayout.measureVertical(LinearLayout.java:763)
                                                       at android.widget.LinearLayout.onMeasure(LinearLayout.java:628)
                                                       at android.view.View.measure(View.java:16892)
                                                       at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:940)
                                                       at android.view.View.measure(View.java:16892)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5394)
                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:340)
                                                       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                       at android.view.View.measure(View.java:16892)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5394)
                                                       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1647)
                                                       at android.widget.LinearLayout.measureVertical(LinearLayout.java:763)
                                                       at android.widget.LinearLayout.onMeasure(LinearLayout.java:628)
                                                       at android.view.View.measure(View.java:16892)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5394)
                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:340)
                                                       at android.view.View.measure(View.java:16892)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5394)
                                                       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1647)
                                                       at android.widget.LinearLayout.measureVertical(LinearLayout.java:763)
                                                       at android.widget.LinearLayout.onMeasure(LinearLayout.java:628)
                                                       at android.view.View.measure(View.java:16892)
                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5394)
                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:340)
                                                       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2363)
                                                       at android.view.View.measure(View.java:16892)
                                                       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2289)
                                                       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1333)
                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1530)
                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1210)
                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6408)
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:807)
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:610)
                                                       at android.view.Choreographer.doFrame(Choreographer.java:578)
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:793)
                                                       at android.os.Handler.handleCallback(Handler.java:808)
                                                       at android.os.Handler.dispatchMessage(Handler.java:103)
                                                   	at android.os.Looper.loop(Looper

**Comment by saiwu-bigkoo** [comment]
convenientBanner.setOnItemClickListener是不是调用在setPages 之前了？

**Comment by pickyourself** [comment]
在setPages之后不报空指针 但是用在listview的headview 里时 这个方法点击没有效果啊

**Comment by saiwu-bigkoo** [comment]
你可以查看我demo里面的recyclerviewdemo，里面使用recyclerview add Header的，可以参考下。

**Comment by pickyourself** [comment]
恩恩，谢谢

**Comment by saiwu-bigkoo** [comment]
我更新了2.0.2版本，可能之前的OnItemClick有问题，我已经修复了，而且你可以看例子中增加了 addHeader 的例子。

**Comment by pickyourself** [comment]
更新后还是没有效果的

**Comment by saiwu-bigkoo** [comment]
倒，可我demo里面有提供例子呀，我通过例子测试是没有问题的，你再仔细看看哪里错了，或者你把你的例子发给我看看
